[Interface]
    PrivateKey = OPq/AXCT0ie5pBqNo4tk/Oukwa8P7zr3VJREbYlHpng=
    Address = 10.0.0.8/24
    DNS = 1.1.1.1

    [Peer]
    PublicKey = VEzaP1yqDodo2GbgeO/jbtOqyVw34b/nKscRI49FfGQ=
    Endpoint = 13.53.214.109:51820
    AllowedIPs = 0.0.0.0/0
    PersistentKeepalive = 25
    