[Interface]
    PrivateKey = 4F1hi4Npledg4Nf+OlGRzU4Vrn2k1hvUiR5ydKVBrlA=
    Address = 10.0.0.7/24
    DNS = 1.1.1.1

    [Peer]
    PublicKey = VEzaP1yqDodo2GbgeO/jbtOqyVw34b/nKscRI49FfGQ=
    Endpoint = 13.53.214.109:51820
    AllowedIPs = 0.0.0.0/0
    PersistentKeepalive = 25
    